//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace DGWSMortalitySTS.Mortality {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MortalityRegistrationServiceBinding", Namespace="http://rep.oio.dk/sst.dk/xml.wsdl/2008.10.10/")]
    public partial class MortalityRegistrationService : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback ReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MortalityRegistrationService() {
            this.Url = global::DGWSMortalitySTS.Properties.Settings.Default.DGWSMortalitySTS_Mortality_MortalityRegistrationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReportCompletedEventHandler ReportCompleted;
        
        /// <remarks/>
        public event RemoveReportCompletedEventHandler RemoveReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rep.oio.dk/sst.dk/xml.wsdl/2008.10.10/#Report", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MortalityAnswer", Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
        public string Report([System.Xml.Serialization.XmlElementAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")] MortalityReasonType MortalityReason) {
            object[] results = this.Invoke("Report", new object[] {
                        MortalityReason});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReportAsync(MortalityReasonType MortalityReason) {
            this.ReportAsync(MortalityReason, null);
        }
        
        /// <remarks/>
        public void ReportAsync(MortalityReasonType MortalityReason, object userState) {
            if ((this.ReportOperationCompleted == null)) {
                this.ReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportOperationCompleted);
            }
            this.InvokeAsync("Report", new object[] {
                        MortalityReason}, this.ReportOperationCompleted, userState);
        }
        
        private void OnReportOperationCompleted(object arg) {
            if ((this.ReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportCompleted(this, new ReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rep.oio.dk/sst.dk/xml.wsdl/2008.10.10/#RemoveReport", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("DeleteResult", Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
        public bool RemoveReport([System.Xml.Serialization.XmlElementAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")] string SchemaID) {
            object[] results = this.Invoke("RemoveReport", new object[] {
                        SchemaID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveReportAsync(string SchemaID) {
            this.RemoveReportAsync(SchemaID, null);
        }
        
        /// <remarks/>
        public void RemoveReportAsync(string SchemaID, object userState) {
            if ((this.RemoveReportOperationCompleted == null)) {
                this.RemoveReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveReportOperationCompleted);
            }
            this.InvokeAsync("RemoveReport", new object[] {
                        SchemaID}, this.RemoveReportOperationCompleted, userState);
        }
        
        private void OnRemoveReportOperationCompleted(object arg) {
            if ((this.RemoveReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveReportCompleted(this, new RemoveReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class MortalityReasonType {
        
        private string schemaIDField;
        
        private PersonIdentifierType personIdentifierField;
        
        private Part1And2Type part1And2Field;
        
        /// <remarks/>
        public string SchemaID {
            get {
                return this.schemaIDField;
            }
            set {
                this.schemaIDField = value;
            }
        }
        
        /// <remarks/>
        public PersonIdentifierType PersonIdentifier {
            get {
                return this.personIdentifierField;
            }
            set {
                this.personIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public Part1And2Type Part1And2 {
            get {
                return this.part1And2Field;
            }
            set {
                this.part1And2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class PersonIdentifierType {
        
        private object itemField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PersonCivilRegistrationIdentifier", typeof(string), Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/")]
        [System.Xml.Serialization.XmlElementAttribute("NoPersonCivilRegistrationIdentifier", typeof(NoPersonCivilRegistrationIdentifierType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class NoPersonCivilRegistrationIdentifierType {
        
        private PersonGenderCodeType personGenderCodeField;
        
        private string personCivilRegistrationReplacementIdentifierField;
        
        private PersonNameStructureType personNameStructureField;
        
        private AddressPostalType addressPostalField;
        
        private System.DateTime birthDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/")]
        public PersonGenderCodeType PersonGenderCode {
            get {
                return this.personGenderCodeField;
            }
            set {
                this.personGenderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/2007/01/02/")]
        public string PersonCivilRegistrationReplacementIdentifier {
            get {
                return this.personCivilRegistrationReplacementIdentifierField;
            }
            set {
                this.personCivilRegistrationReplacementIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/")]
        public PersonNameStructureType PersonNameStructure {
            get {
                return this.personNameStructureField;
            }
            set {
                this.personNameStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
        public AddressPostalType AddressPostal {
            get {
                return this.addressPostalField;
            }
            set {
                this.addressPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", DataType="date")]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/")]
    public enum PersonGenderCodeType {
        
        /// <remarks/>
        male,
        
        /// <remarks/>
        female,
        
        /// <remarks/>
        unspecified,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/")]
    public partial class PersonNameStructureType {
        
        private string personGivenNameField;
        
        private string personMiddleNameField;
        
        private string personSurnameNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string PersonGivenName {
            get {
                return this.personGivenNameField;
            }
            set {
                this.personGivenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string PersonMiddleName {
            get {
                return this.personMiddleNameField;
            }
            set {
                this.personMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string PersonSurnameName {
            get {
                return this.personSurnameNameField;
            }
            set {
                this.personSurnameNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class AcmeType {
        
        private string iCD10CodeField;
        
        private bool lookupField;
        
        /// <remarks/>
        public string ICD10Code {
            get {
                return this.iCD10CodeField;
            }
            set {
                this.iCD10CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool lookup {
            get {
                return this.lookupField;
            }
            set {
                this.lookupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class JudicialAutopsyType {
        
        private string autopsyFindingsField;
        
        private string investmentsConclusionsField;
        
        /// <remarks/>
        public string AutopsyFindings {
            get {
                return this.autopsyFindingsField;
            }
            set {
                this.autopsyFindingsField = value;
            }
        }
        
        /// <remarks/>
        public string InvestmentsConclusions {
            get {
                return this.investmentsConclusionsField;
            }
            set {
                this.investmentsConclusionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class AutopsyType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HospitalAutopsy", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("JudicialAutopsy", typeof(JudicialAutopsyType))]
        [System.Xml.Serialization.XmlElementAttribute("NoAutopsyTextReason", typeof(NoAutopsyTextReasonType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public enum NoAutopsyTextReasonType {
        
        /// <remarks/>
        ProhibitedAutopsy,
        
        /// <remarks/>
        NoAutopsy,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class DeathNonNaturalType {
        
        private PlaceOfEventType placeOfEventField;
        
        /// <remarks/>
        public PlaceOfEventType PlaceOfEvent {
            get {
                return this.placeOfEventField;
            }
            set {
                this.placeOfEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public enum PlaceOfEventType {
        
        /// <remarks/>
        tranportationarea,
        
        /// <remarks/>
        livingarea,
        
        /// <remarks/>
        productionarea,
        
        /// <remarks/>
        shoppingarea,
        
        /// <remarks/>
        educationarea,
        
        /// <remarks/>
        sportsarea,
        
        /// <remarks/>
        Amusementandparkarea,
        
        /// <remarks/>
        OpenNature,
        
        /// <remarks/>
        SeaOrLake,
        
        /// <remarks/>
        Otherplace,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class ATCElementType {
        
        private string aTCTextField;
        
        private string aTCCodeField;
        
        /// <remarks/>
        public string ATCText {
            get {
                return this.aTCTextField;
            }
            set {
                this.aTCTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NMTOKEN")]
        public string ATCCode {
            get {
                return this.aTCCodeField;
            }
            set {
                this.aTCCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class CauseOfDeathType {
        
        private string causeOfDeathField;
        
        private string durationBeforeDeathField;
        
        private uint versionField;
        
        /// <remarks/>
        public string CauseOfDeath {
            get {
                return this.causeOfDeathField;
            }
            set {
                this.causeOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration")]
        public string DurationBeforeDeath {
            get {
                return this.durationBeforeDeathField;
            }
            set {
                this.durationBeforeDeathField = value;
            }
        }
        
        /// <remarks/>
        public uint Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class Part2Type {
        
        private System.DateTime createdField;
        
        private WayOfDeathType wayOfDeathField;
        
        private CauseOfDeathType[] primaryCauseOfDeathField;
        
        private CauseOfDeathType[] secondaryCauseOfDeathField;
        
        private ATCElementType[] productnameATCCodeField;
        
        private DeathNonNaturalType deathNonNaturalField;
        
        private AutopsyType autopsyField;
        
        private string supplementalTextField;
        
        private AcmeType acmeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public WayOfDeathType WayOfDeath {
            get {
                return this.wayOfDeathField;
            }
            set {
                this.wayOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CauseOfDeath", IsNullable=false)]
        public CauseOfDeathType[] PrimaryCauseOfDeath {
            get {
                return this.primaryCauseOfDeathField;
            }
            set {
                this.primaryCauseOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CauseOfDeath", IsNullable=false)]
        public CauseOfDeathType[] SecondaryCauseOfDeath {
            get {
                return this.secondaryCauseOfDeathField;
            }
            set {
                this.secondaryCauseOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProductnameATCCode")]
        public ATCElementType[] ProductnameATCCode {
            get {
                return this.productnameATCCodeField;
            }
            set {
                this.productnameATCCodeField = value;
            }
        }
        
        /// <remarks/>
        public DeathNonNaturalType DeathNonNatural {
            get {
                return this.deathNonNaturalField;
            }
            set {
                this.deathNonNaturalField = value;
            }
        }
        
        /// <remarks/>
        public AutopsyType Autopsy {
            get {
                return this.autopsyField;
            }
            set {
                this.autopsyField = value;
            }
        }
        
        /// <remarks/>
        public string SupplementalText {
            get {
                return this.supplementalTextField;
            }
            set {
                this.supplementalTextField = value;
            }
        }
        
        /// <remarks/>
        public AcmeType Acme {
            get {
                return this.acmeField;
            }
            set {
                this.acmeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public enum WayOfDeathType {
        
        /// <remarks/>
        natural,
        
        /// <remarks/>
        accident,
        
        /// <remarks/>
        kill,
        
        /// <remarks/>
        suicide,
        
        /// <remarks/>
        unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class AlternativeDoctorType {
        
        private PersonNameStructureType personNameStructureField;
        
        private AddressPostalType doctorAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/itst.dk/xml/schemas/2006/01/17/")]
        public PersonNameStructureType PersonNameStructure {
            get {
                return this.personNameStructureField;
            }
            set {
                this.personNameStructureField = value;
            }
        }
        
        /// <remarks/>
        public AddressPostalType DoctorAddress {
            get {
                return this.doctorAddressField;
            }
            set {
                this.doctorAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
    public partial class AddressPostalType {
        
        private string mailDeliverySublocationIdentifierField;
        
        private string streetNameField;
        
        private string streetNameForAddressingNameField;
        
        private string streetBuildingIdentifierField;
        
        private string floorIdentifierField;
        
        private string suiteIdentifierField;
        
        private string districtSubdivisionIdentifierField;
        
        private string postOfficeBoxIdentifierField;
        
        private string postCodeIdentifierField;
        
        private string districtNameField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string MailDeliverySublocationIdentifier {
            get {
                return this.mailDeliverySublocationIdentifierField;
            }
            set {
                this.mailDeliverySublocationIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/")]
        public string StreetNameForAddressingName {
            get {
                return this.streetNameForAddressingNameField;
            }
            set {
                this.streetNameForAddressingNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string StreetBuildingIdentifier {
            get {
                return this.streetBuildingIdentifierField;
            }
            set {
                this.streetBuildingIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string FloorIdentifier {
            get {
                return this.floorIdentifierField;
            }
            set {
                this.floorIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public string SuiteIdentifier {
            get {
                return this.suiteIdentifierField;
            }
            set {
                this.suiteIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")]
        public string DistrictSubdivisionIdentifier {
            get {
                return this.districtSubdivisionIdentifierField;
            }
            set {
                this.districtSubdivisionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/13/", DataType="integer")]
        public string PostOfficeBoxIdentifier {
            get {
                return this.postOfficeBoxIdentifierField;
            }
            set {
                this.postOfficeBoxIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")]
        public string PostCodeIdentifier {
            get {
                return this.postCodeIdentifierField;
            }
            set {
                this.postCodeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
        public CountryIdentificationCodeType CountryIdentificationCode {
            get {
                return this.countryIdentificationCodeField;
            }
            set {
                this.countryIdentificationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType {
        
        private _CountryIdentificationSchemeType schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,
        
        /// <remarks/>
        imk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class TimeOfDeathType {
        
        private DateTimeOrDateType dateTimeOrDateField;
        
        private DeathSiteType deathSiteField;
        
        /// <remarks/>
        public DateTimeOrDateType DateTimeOrDate {
            get {
                return this.dateTimeOrDateField;
            }
            set {
                this.dateTimeOrDateField = value;
            }
        }
        
        /// <remarks/>
        public DeathSiteType DeathSite {
            get {
                return this.deathSiteField;
            }
            set {
                this.deathSiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class DateTimeOrDateType {
        
        private System.DateTime itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Date", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public System.DateTime Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        DateTime,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class DeathSiteType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HospitalIdentifier", typeof(HospitalIdentifierType))]
        [System.Xml.Serialization.XmlElementAttribute("KnownAddress", typeof(AddressPostalType))]
        [System.Xml.Serialization.XmlElementAttribute("OtherPlaceOfDeath", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Residence", typeof(ResidenceType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class HospitalIdentifierType {
        
        private string hospitalClasifikationField;
        
        private string hospitalDepartmentField;
        
        /// <remarks/>
        public string HospitalClasifikation {
            get {
                return this.hospitalClasifikationField;
            }
            set {
                this.hospitalClasifikationField = value;
            }
        }
        
        /// <remarks/>
        public string HospitalDepartment {
            get {
                return this.hospitalDepartmentField;
            }
            set {
                this.hospitalDepartmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public enum ResidenceType {
        
        /// <remarks/>
        Home,
        
        /// <remarks/>
        NurseryHome,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class FindingSiteType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FindingKnownAddress", typeof(AddressPostalType))]
        [System.Xml.Serialization.XmlElementAttribute("FindingOtherPlaceOfDeath", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("FindingResidence", typeof(ResidenceType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class FindingTimeType {
        
        private DateTimeOrDateType dateTimeOrDateField;
        
        private DeathSiteType deathSiteField;
        
        private FindingSiteType findingSiteField;
        
        /// <remarks/>
        public DateTimeOrDateType DateTimeOrDate {
            get {
                return this.dateTimeOrDateField;
            }
            set {
                this.dateTimeOrDateField = value;
            }
        }
        
        /// <remarks/>
        public DeathSiteType DeathSite {
            get {
                return this.deathSiteField;
            }
            set {
                this.deathSiteField = value;
            }
        }
        
        /// <remarks/>
        public FindingSiteType FindingSite {
            get {
                return this.findingSiteField;
            }
            set {
                this.findingSiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class BornDeadDataType {
        
        private System.DateTime birthdateField;
        
        private PersonGenderCodeType personGenderCodeField;
        
        /// <remarks/>
        public System.DateTime Birthdate {
            get {
                return this.birthdateField;
            }
            set {
                this.birthdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/")]
        public PersonGenderCodeType PersonGenderCode {
            get {
                return this.personGenderCodeField;
            }
            set {
                this.personGenderCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class Part1Type {
        
        private System.DateTime createdField;
        
        private string healthInsuranceNumberField;
        
        private bool bornDeadField;
        
        private BornDeadDataType bornDeadDataField;
        
        private object itemField;
        
        private SignOfDeathType signOfDeathField;
        
        private System.DateTime inquestDateField;
        
        private bool policeContactField;
        
        private ImplantsType implantsField;
        
        private AlternativeDoctorType alternativeDoctorField;
        
        private string policeStationNameField;
        
        private bool page2WillFollowField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string HealthInsuranceNumber {
            get {
                return this.healthInsuranceNumberField;
            }
            set {
                this.healthInsuranceNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool BornDead {
            get {
                return this.bornDeadField;
            }
            set {
                this.bornDeadField = value;
            }
        }
        
        /// <remarks/>
        public BornDeadDataType BornDeadData {
            get {
                return this.bornDeadDataField;
            }
            set {
                this.bornDeadDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FindingTime", typeof(FindingTimeType))]
        [System.Xml.Serialization.XmlElementAttribute("TimeOfDeath", typeof(TimeOfDeathType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public SignOfDeathType SignOfDeath {
            get {
                return this.signOfDeathField;
            }
            set {
                this.signOfDeathField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InquestDate {
            get {
                return this.inquestDateField;
            }
            set {
                this.inquestDateField = value;
            }
        }
        
        /// <remarks/>
        public bool PoliceContact {
            get {
                return this.policeContactField;
            }
            set {
                this.policeContactField = value;
            }
        }
        
        /// <remarks/>
        public ImplantsType Implants {
            get {
                return this.implantsField;
            }
            set {
                this.implantsField = value;
            }
        }
        
        /// <remarks/>
        public AlternativeDoctorType AlternativeDoctor {
            get {
                return this.alternativeDoctorField;
            }
            set {
                this.alternativeDoctorField = value;
            }
        }
        
        /// <remarks/>
        public string PoliceStationName {
            get {
                return this.policeStationNameField;
            }
            set {
                this.policeStationNameField = value;
            }
        }
        
        /// <remarks/>
        public bool Page2WillFollow {
            get {
                return this.page2WillFollowField;
            }
            set {
                this.page2WillFollowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public enum SignOfDeathType {
        
        /// <remarks/>
        Rigor,
        
        /// <remarks/>
        Livores,
        
        /// <remarks/>
        LivoresAndRigor,
        
        /// <remarks/>
        Cadaverositas,
        
        /// <remarks/>
        CadaverositasAndRigor,
        
        /// <remarks/>
        CadaverositasAndLivores,
        
        /// <remarks/>
        CadaverositasAndLivoresAndRigor,
        
        /// <remarks/>
        Maceratio,
        
        /// <remarks/>
        MaceratioAndRigor,
        
        /// <remarks/>
        MaceratioAndLivores,
        
        /// <remarks/>
        MaceratioAndLivoresAndRigor,
        
        /// <remarks/>
        MaceratioAndCadaverositas,
        
        /// <remarks/>
        MaceratioAndCadaverositasAndRigor,
        
        /// <remarks/>
        MaceratioAndCadaverositasAndLivores,
        
        /// <remarks/>
        MaceratioAndCadaverositasAndLivoresAndRigor,
        
        /// <remarks/>
        Other,
        
        /// <remarks/>
        OtherAndRigor,
        
        /// <remarks/>
        OtherAndLivores,
        
        /// <remarks/>
        OtherAndLivoresAndRigor,
        
        /// <remarks/>
        OtherAndCadaverositas,
        
        /// <remarks/>
        OtherAndCadaverositasAndRigor,
        
        /// <remarks/>
        OtherAndCadaverositasAndLivores,
        
        /// <remarks/>
        OtherAndCadaverositasAndLivoresAndRigor,
        
        /// <remarks/>
        OtherAndMaceratio,
        
        /// <remarks/>
        OtherAndMaceratioAndRigor,
        
        /// <remarks/>
        OtherAndMaceratioAndLivores,
        
        /// <remarks/>
        OtherAndMaceratioAndLivoresAndRigor,
        
        /// <remarks/>
        OtherAndMaceratioAndCadaverositas,
        
        /// <remarks/>
        OtherAndMaceratioAndCadaverositasAndRigor,
        
        /// <remarks/>
        OtherAndMaceratioAndCadaverositasAndLivores,
        
        /// <remarks/>
        OtherAndMaceratioAndCadaverositasAndLivoresAndRigor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public enum ImplantsType {
        
        /// <remarks/>
        YesAndRemoved,
        
        /// <remarks/>
        YesAndNotRemoved,
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public partial class Part1And2Type {
        
        private DoctorFunctionType doctorFunctionField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public DoctorFunctionType DoctorFunction {
            get {
                return this.doctorFunctionField;
            }
            set {
                this.doctorFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Part1", typeof(Part1Type))]
        [System.Xml.Serialization.XmlElementAttribute("Part2", typeof(Part2Type))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sst.dk/Mortality/xml.schema/2008.04.03")]
    public enum DoctorFunctionType {
        
        /// <remarks/>
        PersonalGP,
        
        /// <remarks/>
        EmergencyGP,
        
        /// <remarks/>
        HospitalDoctor,
        
        /// <remarks/>
        Medicalofficer,
        
        /// <remarks/>
        HospiceDoctor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ReportCompletedEventHandler(object sender, ReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void RemoveReportCompletedEventHandler(object sender, RemoveReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591