//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
// 
namespace SORConsole.dk.imkit.sorwebservice {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SORWSSoap", Namespace="http://www.sst.dk/sor/")]
    public class SORWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public AuthHeader AuthHeaderValue;
        
        /// <remarks/>
        public SORWS() {
            string urlSetting = System.Configuration.ConfigurationSettings.AppSettings["SORConsole.dk.imkit.sorwebservice.SORWS"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://sorwebservice.imkit.dk/SORws.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetParents", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetParents(long sorId) {
            object[] results = this.Invoke("GetParents", new object[] {
                        sorId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetParents(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetParents", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndGetParents(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetSubtree", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetSubtree(long sorId) {
            object[] results = this.Invoke("GetSubtree", new object[] {
                        sorId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSubtree(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSubtree", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndGetSubtree(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetUserSubtrees", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetUserSubtrees(string userName) {
            object[] results = this.Invoke("GetUserSubtrees", new object[] {
                        userName});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserSubtrees(string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserSubtrees", new object[] {
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndGetUserSubtrees(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetUnitType", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUnitType(long sorId) {
            object[] results = this.Invoke("GetUnitType", new object[] {
                        sorId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUnitType(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUnitType", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetUnitType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetSorType", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSorType(long sorId) {
            object[] results = this.Invoke("GetSorType", new object[] {
                        sorId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSorType(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSorType", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetSorType(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetChildren", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetChildren(long sorId) {
            object[] results = this.Invoke("GetChildren", new object[] {
                        sorId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChildren(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChildren", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Xml.XmlNode EndGetChildren(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetChildrenAtNextLevel", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetChildrenAtNextLevel(long sorId) {
            object[] results = this.Invoke("GetChildrenAtNextLevel", new object[] {
                        sorId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetChildrenAtNextLevel(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetChildrenAtNextLevel", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetChildrenAtNextLevel(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetInheritedSpecialities", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorClinicalSpeciality[] GetInheritedSpecialities(long sorId) {
            object[] results = this.Invoke("GetInheritedSpecialities", new object[] {
                        sorId});
            return ((sorClinicalSpeciality[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInheritedSpecialities(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInheritedSpecialities", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorClinicalSpeciality[] EndGetInheritedSpecialities(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorClinicalSpeciality[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetNonInheritedSpecialities", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorClinicalSpeciality[] GetNonInheritedSpecialities(long sorId) {
            object[] results = this.Invoke("GetNonInheritedSpecialities", new object[] {
                        sorId});
            return ((sorClinicalSpeciality[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNonInheritedSpecialities(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNonInheritedSpecialities", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorClinicalSpeciality[] EndGetNonInheritedSpecialities(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorClinicalSpeciality[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetAllSpecialities", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorClinicalSpeciality[] GetAllSpecialities(long sorId) {
            object[] results = this.Invoke("GetAllSpecialities", new object[] {
                        sorId});
            return ((sorClinicalSpeciality[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAllSpecialities(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAllSpecialities", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorClinicalSpeciality[] EndGetAllSpecialities(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorClinicalSpeciality[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetSystemSuppliers", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSystemSuppliers() {
            object[] results = this.Invoke("GetSystemSuppliers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSystemSuppliers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSystemSuppliers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetSystemSuppliers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetHealthInstitutionTypes", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHealthInstitutionTypes() {
            object[] results = this.Invoke("GetHealthInstitutionTypes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetHealthInstitutionTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetHealthInstitutionTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetHealthInstitutionTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetInstitutionOwnerTypes", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetInstitutionOwnerTypes() {
            object[] results = this.Invoke("GetInstitutionOwnerTypes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInstitutionOwnerTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInstitutionOwnerTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetInstitutionOwnerTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetOrganizationalUnitTypes", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetOrganizationalUnitTypes() {
            object[] results = this.Invoke("GetOrganizationalUnitTypes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOrganizationalUnitTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOrganizationalUnitTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetOrganizationalUnitTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetClinicalSpecialities", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetClinicalSpecialities() {
            object[] results = this.Invoke("GetClinicalSpecialities", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetClinicalSpecialities(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetClinicalSpecialities", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetClinicalSpecialities(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetSpecialityTypes", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSpecialityTypes() {
            object[] results = this.Invoke("GetSpecialityTypes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSpecialityTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSpecialityTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetSpecialityTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetCommunicationSuppliers", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetCommunicationSuppliers() {
            object[] results = this.Invoke("GetCommunicationSuppliers", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCommunicationSuppliers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCommunicationSuppliers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetCommunicationSuppliers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetSystemTypes", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSystemTypes() {
            object[] results = this.Invoke("GetSystemTypes", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSystemTypes(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSystemTypes", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetSystemTypes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/SORSearchUnits", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SORSearchUnits(string userName, string unitNameFilter, string localCodeFilter, long specialityCode) {
            object[] results = this.Invoke("SORSearchUnits", new object[] {
                        userName,
                        unitNameFilter,
                        localCodeFilter,
                        specialityCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSORSearchUnits(string userName, string unitNameFilter, string localCodeFilter, long specialityCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SORSearchUnits", new object[] {
                        userName,
                        unitNameFilter,
                        localCodeFilter,
                        specialityCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSORSearchUnits(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/ValidateUserCredentials", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateUserCredentials(string userName, string password) {
            object[] results = this.Invoke("ValidateUserCredentials", new object[] {
                        userName,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateUserCredentials(string userName, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateUserCredentials", new object[] {
                        userName,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndValidateUserCredentials(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetSORGroup", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSORGroup(string userName) {
            object[] results = this.Invoke("GetSORGroup", new object[] {
                        userName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSORGroup(string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSORGroup", new object[] {
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetSORGroup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetIO", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorInstitutionOwner GetIO(long sorId) {
            object[] results = this.Invoke("GetIO", new object[] {
                        sorId});
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetIO(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetIO", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorInstitutionOwner EndGetIO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetHI", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorHealthInstitution GetHI(long sorId) {
            object[] results = this.Invoke("GetHI", new object[] {
                        sorId});
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetHI(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetHI", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorHealthInstitution EndGetHI(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetOU", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorOrganizationalUnit GetOU(long sorId) {
            object[] results = this.Invoke("GetOU", new object[] {
                        sorId});
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOU(long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOU", new object[] {
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorOrganizationalUnit EndGetOU(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/CreateIO", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorInstitutionOwner CreateIO(sorInstitutionOwner IO) {
            object[] results = this.Invoke("CreateIO", new object[] {
                        IO});
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateIO(sorInstitutionOwner IO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateIO", new object[] {
                        IO}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorInstitutionOwner EndCreateIO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/CreateHI", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorHealthInstitution CreateHI(sorHealthInstitution HI) {
            object[] results = this.Invoke("CreateHI", new object[] {
                        HI});
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateHI(sorHealthInstitution HI, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateHI", new object[] {
                        HI}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorHealthInstitution EndCreateHI(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/CreateOU", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorOrganizationalUnit CreateOU(sorOrganizationalUnit OU) {
            object[] results = this.Invoke("CreateOU", new object[] {
                        OU});
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateOU(sorOrganizationalUnit OU, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateOU", new object[] {
                        OU}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorOrganizationalUnit EndCreateOU(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/EditIO", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorInstitutionOwner EditIO(sorInstitutionOwner IO) {
            object[] results = this.Invoke("EditIO", new object[] {
                        IO});
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEditIO(sorInstitutionOwner IO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EditIO", new object[] {
                        IO}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorInstitutionOwner EndEditIO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/EditOU", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorOrganizationalUnit EditOU(sorOrganizationalUnit OU) {
            object[] results = this.Invoke("EditOU", new object[] {
                        OU});
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEditOU(sorOrganizationalUnit OU, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EditOU", new object[] {
                        OU}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorOrganizationalUnit EndEditOU(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/EditHI", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorHealthInstitution EditHI(sorHealthInstitution HI) {
            object[] results = this.Invoke("EditHI", new object[] {
                        HI});
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginEditHI(sorHealthInstitution HI, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EditHI", new object[] {
                        HI}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorHealthInstitution EndEditHI(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/ValidateIO", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorInstitutionOwner ValidateIO(sorInstitutionOwner IO) {
            object[] results = this.Invoke("ValidateIO", new object[] {
                        IO});
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateIO(sorInstitutionOwner IO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateIO", new object[] {
                        IO}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorInstitutionOwner EndValidateIO(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorInstitutionOwner)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/ValidateHI", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorHealthInstitution ValidateHI(sorHealthInstitution HI) {
            object[] results = this.Invoke("ValidateHI", new object[] {
                        HI});
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateHI(sorHealthInstitution HI, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateHI", new object[] {
                        HI}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorHealthInstitution EndValidateHI(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorHealthInstitution)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/ValidateOU", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorOrganizationalUnit ValidateOU(sorOrganizationalUnit OU) {
            object[] results = this.Invoke("ValidateOU", new object[] {
                        OU});
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateOU(sorOrganizationalUnit OU, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateOU", new object[] {
                        OU}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorOrganizationalUnit EndValidateOU(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorOrganizationalUnit)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/Search", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public sorSearchResult[] Search(sorSearch searchParameters) {
            object[] results = this.Invoke("Search", new object[] {
                        searchParameters});
            return ((sorSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSearch(sorSearch searchParameters, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Search", new object[] {
                        searchParameters}, callback, asyncState);
        }
        
        /// <remarks/>
        public sorSearchResult[] EndSearch(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((sorSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetHistory", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetHistory(long longSorID) {
            object[] results = this.Invoke("GetHistory", new object[] {
                        longSorID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetHistory(long longSorID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetHistory", new object[] {
                        longSorID}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetHistory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/CloseEntity", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CloseEntity(long sorId, System.DateTime dtToDate) {
            object[] results = this.Invoke("CloseEntity", new object[] {
                        sorId,
                        dtToDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCloseEntity(long sorId, System.DateTime dtToDate, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CloseEntity", new object[] {
                        sorId,
                        dtToDate}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndCloseEntity(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetTableAll", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTableAll(string tableName) {
            object[] results = this.Invoke("GetTableAll", new object[] {
                        tableName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableAll(string tableName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableAll", new object[] {
                        tableName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetTableAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetTable", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTable(string tableName) {
            object[] results = this.Invoke("GetTable", new object[] {
                        tableName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTable(string tableName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTable", new object[] {
                        tableName}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetTable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/FLPRGetTableDelta", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FLPRGetTableDelta(string tableName, System.DateTime from) {
            object[] results = this.Invoke("FLPRGetTableDelta", new object[] {
                        tableName,
                        from});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFLPRGetTableDelta(string tableName, System.DateTime from, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FLPRGetTableDelta", new object[] {
                        tableName,
                        from}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndFLPRGetTableDelta(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/FLPRGetTableAt", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet FLPRGetTableAt(string tableName, System.DateTime atTime) {
            object[] results = this.Invoke("FLPRGetTableAt", new object[] {
                        tableName,
                        atTime});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFLPRGetTableAt(string tableName, System.DateTime atTime, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FLPRGetTableAt", new object[] {
                        tableName,
                        atTime}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndFLPRGetTableAt(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/FLPRUploadDelta", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FLPRUploadDelta(System.DateTime fromDate, string serverURI, OUTPUT_FORMAT format, string userName, string password) {
            object[] results = this.Invoke("FLPRUploadDelta", new object[] {
                        fromDate,
                        serverURI,
                        format,
                        userName,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFLPRUploadDelta(System.DateTime fromDate, string serverURI, OUTPUT_FORMAT format, string userName, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FLPRUploadDelta", new object[] {
                        fromDate,
                        serverURI,
                        format,
                        userName,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndFLPRUploadDelta(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/FLPRUpload", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FLPRUpload(System.DateTime atTime, OUTPUT_FORMAT format, string serverURI, string userName, string password) {
            object[] results = this.Invoke("FLPRUpload", new object[] {
                        atTime,
                        format,
                        serverURI,
                        userName,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFLPRUpload(System.DateTime atTime, OUTPUT_FORMAT format, string serverURI, string userName, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FLPRUpload", new object[] {
                        atTime,
                        format,
                        serverURI,
                        userName,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndFLPRUpload(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetUserRightsAll", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long[] GetUserRightsAll(string userName) {
            object[] results = this.Invoke("GetUserRightsAll", new object[] {
                        userName});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserRightsAll(string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserRightsAll", new object[] {
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public long[] EndGetUserRightsAll(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetUserRightsTop", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long[] GetUserRightsTop(string userName) {
            object[] results = this.Invoke("GetUserRightsTop", new object[] {
                        userName});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserRightsTop(string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserRightsTop", new object[] {
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public long[] EndGetUserRightsTop(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sst.dk/sor/GetUserRights", RequestNamespace="http://www.sst.dk/sor/", ResponseNamespace="http://www.sst.dk/sor/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetUserRights(string userName, long sorId) {
            object[] results = this.Invoke("GetUserRights", new object[] {
                        userName,
                        sorId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserRights(string userName, long sorId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserRights", new object[] {
                        userName,
                        sorId}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndGetUserRights(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sst.dk/sor/", IsNullable=false)]
    public class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string strUserName;
        
        /// <remarks/>
        public string strPassword;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorSearchResult {
        
        /// <remarks/>
        public long entity_code;
        
        /// <remarks/>
        public string entity_type;
        
        /// <remarks/>
        public string entity_name;
        
        /// <remarks/>
        public string pa_phone_number;
        
        /// <remarks/>
        public string va_website;
        
        /// <remarks/>
        public string pa_street_name;
        
        /// <remarks/>
        public string pa_street_building_id;
        
        /// <remarks/>
        public string pa_floor_id;
        
        /// <remarks/>
        public string pa_suite_id;
        
        /// <remarks/>
        public string pa_post_code_id;
        
        /// <remarks/>
        public string pa_district_name;
        
        /// <remarks/>
        public string owner_name;
        
        /// <remarks/>
        public long owner_code;
        
        /// <remarks/>
        public string institution_name;
        
        /// <remarks/>
        public long institution_code;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorSearch {
        
        /// <remarks/>
        public long speciality;
        
        /// <remarks/>
        public string organizationName;
        
        /// <remarks/>
        public long sorId;
        
        /// <remarks/>
        public System.DateTime dtFromDate;
        
        /// <remarks/>
        public long longEanLocationCode;
        
        /// <remarks/>
        public long longCommunicationSupplier;
        
        /// <remarks/>
        public long longSystemType;
        
        /// <remarks/>
        public long longSystemSupplier;
        
        /// <remarks/>
        public bool strCanRcvCorrespondance;
        
        /// <remarks/>
        public bool strCanRcvReferral;
        
        /// <remarks/>
        public bool strCanRcvEpiCrisis;
        
        /// <remarks/>
        public bool strCanRcvOpEPIcrisis;
        
        /// <remarks/>
        public string strProviderId;
        
        /// <remarks/>
        public long longOrganizationType;
        
        /// <remarks/>
        public long longRegion;
        
        /// <remarks/>
        public string strPostCodeIDFrom;
        
        /// <remarks/>
        public string strPostCodeIDTo;
        
        /// <remarks/>
        public string strShak1Code;
        
        /// <remarks/>
        public string strLocalCode;
        
        /// <remarks/>
        public bool boolClosedUnits;
        
        /// <remarks/>
        public bool boolMyUnits;
        
        /// <remarks/>
        public string strUserName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorOrganizationalUnit {
        
        /// <remarks/>
        public string strName;
        
        /// <remarks/>
        public long longSorCode;
        
        /// <remarks/>
        public long longType;
        
        /// <remarks/>
        public string strLocalCode;
        
        /// <remarks/>
        public string strShak1Code;
        
        /// <remarks/>
        public string strProviderID;
        
        /// <remarks/>
        public sorPhysicalAddress paPostal;
        
        /// <remarks/>
        public sorPhysicalAddress paVisiting;
        
        /// <remarks/>
        public sorPhysicalAddress paActivity;
        
        /// <remarks/>
        public sorVirtualAddress vaVirtual;
        
        /// <remarks/>
        public sorClinicalSpeciality[] csarrSpecialities;
        
        /// <remarks/>
        public sorClinicalSpeciality[] csarrInheritedSpecialities;
        
        /// <remarks/>
        public string strNurseResp;
        
        /// <remarks/>
        public string strAdmitted;
        
        /// <remarks/>
        public int intBedCapacity;
        
        /// <remarks/>
        public string strOutpatient;
        
        /// <remarks/>
        public string strDoctors;
        
        /// <remarks/>
        public string strNurses;
        
        /// <remarks/>
        public string strPatServices;
        
        /// <remarks/>
        public string strAttendances;
        
        /// <remarks/>
        public long longParentSorCode;
        
        /// <remarks/>
        public System.DateTime dtFromDate;
        
        /// <remarks/>
        public System.DateTime dtToDate;
        
        /// <remarks/>
        public string strUpdatedBy;
        
        /// <remarks/>
        public System.DateTime dtUpdatedAt;
        
        /// <remarks/>
        public string strParentSORType;
        
        /// <remarks/>
        public string strParentName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorPhysicalAddress {
        
        /// <remarks/>
        public string strStreetName;
        
        /// <remarks/>
        public string strStreetBuildingID;
        
        /// <remarks/>
        public string strFloorID;
        
        /// <remarks/>
        public string strSuiteID;
        
        /// <remarks/>
        public string strPostCodeID;
        
        /// <remarks/>
        public string strDistrictName;
        
        /// <remarks/>
        public string strCountryCodeID;
        
        /// <remarks/>
        public string strMunicipalityCode;
        
        /// <remarks/>
        public string strStreetCode;
        
        /// <remarks/>
        public string strAddressAccessID;
        
        /// <remarks/>
        public string strNote;
        
        /// <remarks/>
        public bool boolInherited;
        
        /// <remarks/>
        public bool boolSkipAddressValidation;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorVirtualAddress {
        
        /// <remarks/>
        public string strCanRcvEpiCrisis;
        
        /// <remarks/>
        public string strCanRcvOpEPIcrisis;
        
        /// <remarks/>
        public string strCanRcvCorrespondance;
        
        /// <remarks/>
        public string strCanRcvReferral;
        
        /// <remarks/>
        public string strContactPerson;
        
        /// <remarks/>
        public string strContactPhoneNumber;
        
        /// <remarks/>
        public string strContactEmailAddress;
        
        /// <remarks/>
        public string strOnlyInternal;
        
        /// <remarks/>
        public string strNonActive;
        
        /// <remarks/>
        public long longEanLocationCode;
        
        /// <remarks/>
        public long longSystemSupplier;
        
        /// <remarks/>
        public long longSystemType;
        
        /// <remarks/>
        public long longCommunicationSupplier;
        
        /// <remarks/>
        public string strEmailAddress;
        
        /// <remarks/>
        public string strWebsite;
        
        /// <remarks/>
        public string strPhoneNumber;
        
        /// <remarks/>
        public string strFaxNumber;
        
        /// <remarks/>
        public string strNote;
        
        /// <remarks/>
        public bool boolInherited;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorClinicalSpeciality {
        
        /// <remarks/>
        public long longSpecialityCode;
        
        /// <remarks/>
        public long longSpecialityType;
        
        /// <remarks/>
        public string strSpecialityValue;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorHealthInstitution {
        
        /// <remarks/>
        public string strName;
        
        /// <remarks/>
        public long longSorCode;
        
        /// <remarks/>
        public long longType;
        
        /// <remarks/>
        public string strShak1Code;
        
        /// <remarks/>
        public sorPhysicalAddress paPostal;
        
        /// <remarks/>
        public sorPhysicalAddress paVisiting;
        
        /// <remarks/>
        public sorVirtualAddress vaVirtual;
        
        /// <remarks/>
        public long longParentSorCode;
        
        /// <remarks/>
        public System.DateTime dtFromDate;
        
        /// <remarks/>
        public System.DateTime dtToDate;
        
        /// <remarks/>
        public string strUpdatedBy;
        
        /// <remarks/>
        public System.DateTime dtUpdatedAt;
        
        /// <remarks/>
        public string strParentName;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public class sorInstitutionOwner {
        
        /// <remarks/>
        public string strName;
        
        /// <remarks/>
        public long longSorCode;
        
        /// <remarks/>
        public long longType;
        
        /// <remarks/>
        public sorPhysicalAddress paPostal;
        
        /// <remarks/>
        public sorVirtualAddress vaVirtual;
        
        /// <remarks/>
        public System.DateTime dtFromDate;
        
        /// <remarks/>
        public System.DateTime dtToDate;
        
        /// <remarks/>
        public string strUpdatedBy;
        
        /// <remarks/>
        public System.DateTime dtUpdatedAt;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sst.dk/sor/")]
    public enum OUTPUT_FORMAT {
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        CSV,
    }
}
